### Get Запрос Users
GET http://127.0.0.1:10001/users/
Content-Type: application/json

### Get Запрос Genres
GET http://127.0.0.1:10001/genres/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

### Get Запрос Genres
GET http://127.0.0.1:10001/genres/19
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

### Get Запрос movies
GET http://127.0.0.1:10001/movies/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

### Get Запрос movies
GET http://127.0.0.1:10001/movies/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ


### Post Movies на добавление
POST http://127.0.0.1:10001/movies/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

{
  "description": "Тест",
  "rating": 7.8,
  "title": "Тест",
  "trailer": "Тест",
  "year": 2022,
  "genre_id": 17,
  "director_id": 1
}

### Post Запрос на добавление
POST http://127.0.0.1:10001/genres/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTM2Njd9.2qFk7v8c14LyUbuVWAaPbL1xdtPapicP_Ml1JQT8Ozo

{
  "name": "gentre_test"
}

### Delete
DELETE http://127.0.0.1:10001/genres/18
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTM2Njd9.2qFk7v8c14LyUbuVWAaPbL1xdtPapicP_Ml1JQT8Ozo


### PUT
PUT http://127.0.0.1:10001/genres/18
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTM2Njd9.2qFk7v8c14LyUbuVWAaPbL1xdtPapicP_Ml1JQT8Ozo
{
  "name": "gentre_test2"
}

###
POST http://127.0.0.1:10001/auth/
Content-Type: application/json

{
  "username": "vasya",
  "password": "my_little_pony"
}

###Create User
POST http://127.0.0.1:10001/auth/register
Content-Type: application/json

{
  "email": "SkyUser1@test.ru",
  "name": "SkyUser1",
  "password": "eGGPtRKS51",
  "role": "user"
}

###login User
POST http://127.0.0.1:10001/auth/login
Content-Type: application/json

{
  "email": "SkyUser1@test.ru",
  "password": "eGGPtRKS51"
}

###login Vasya
POST http://127.0.0.1:10001/auth/login
Content-Type: application/json

{
  "email": "test@vasya1",
  "password": "my_little_pony"
}

###DELETE Users_movies
DELETE http://127.0.0.1:10001/favorites/movies/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

###POST add Users_movies
POST http://127.0.0.1:10001/favorites/movies/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ


###NewPassword
PUT http://127.0.0.1:10001/user/password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

{
  "old_password": "eGGPtRKS51",
  "new_password": "eGGPtRKS52"
}
###GetUsers
GET http://127.0.0.1:10001/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

###PatchUser
PATCH http://127.0.0.1:10001/user/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ

{
  "favorite_genre": 1,
  "name": "SkyUser_test"
}

###DeleteUser
DELETE http://127.0.0.1:10001/user/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDQyNzYyMTAsInJvbGUiOiJ1c2VyIiwidXNlcl9pZCI6MX0.m8mu6tC8HJ1ARPR1jui00WIwXiPktqkZWaib3WmVLqQ



###NewPassword
PUT http://127.0.0.1:10001/auth/login
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDY4NTc4ODAsInJvbGUiOiJ1c2VyIn0.qzNW_FFmMfpmju1eq6jESecbsae-yv5ogKFjsbc6MfY"
}





